### ISSUE TITLE
ICE: Upon handling of imported functions

### ISSUE THREAD

**Issue by Robbepop** [wasm-superopt/rocinante#39]
I just tried `rocinate` super-optimizer on my Wasm file.
However, after parsing and printing the whole contents of the Wasm file onto my terminal I received this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: LinkError([ImportNotFound { namespace: "env", name: "ext_deposit_event" }, ImportNotFound { namespace: "env", name: "ext_scratch_write" }, ImportNotFound { namespace: "env", name: "ext_caller" }, ImportNotFound { namespace: "env", name: "ext_set_storage" }, ImportNotFound { namespace: "env", name: "ext_get_storage" }, ImportNotFound { namespace: "env", name: "ext_scratch_size" }, ImportNotFound { namespace: "env", name: "ext_scratch_read" }, ImportNotFound { namespace: "env", name: "memory" }])', src/exec/wasmer.rs:21:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
So apparently the tool currently cannot handle function imports.
I think best would be to treat those imported functions just as if they produce random output, e.g. return arbitrary values that fit their return type domain.

Or is there another way how I could use `rocinante` with this Wasm file? (I got plenty of similar ones.)

## Backtrace

```
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: core::result::Result<T,E>::unwrap
             at /rustc/6fd8798f4de63328d743eb2a9a9c12e202a4a182/src/libcore/result.rs:1003
  15: rocinante::exec::wasmer::Wasmer::new
             at src/exec/wasmer.rs:21
  16: rocinante::exec::get_interpreter
             at src/exec/mod.rs:46
  17: rocinante::stoke::Superoptimizer::run
             at src/stoke/mod.rs:88
  18: rocinante::main
             at src/main.rs:158
  19: std::rt::lang_start::{{closure}}
             at /rustc/6fd8798f4de63328d743eb2a9a9c12e202a4a182/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  23: std::panicking::try
             at src/libstd/panicking.rs:281
  24: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  25: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  26: std::rt::lang_start
             at /rustc/6fd8798f4de63328d743eb2a9a9c12e202a4a182/src/libstd/rt.rs:67
  27: main
  28: __libc_start_main
  29: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by taegyunkim** [comment]
Hi,

Thanks for interest in my project. This is not at all feature complete and far from production use. It's a research prototype.
